name: Subir reporte

on:
  push:
    branches:
      - main  

jobs:
  upload_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
      working-directory: ${{ github.workspace }}

    - name: Run the script
      run: |
        python import.py  
      env:
        api_key: ${{ secrets.API_KEY }}  

    - name: Upload report
      run: |
        curl -X POST -H "Authorization: Bearer $api_key" \
          -F "file=@$GITHUB_WORKSPACE/your_report.txt" \
          -F "minimum_severity=Info" \
          -F "active=true" \
          -F "verified=true" \
          -F "scan_type=$type_scan" \
          -F "close_old_findings=false" \
          -F "test_title=EdgarPrueba-Pipeline" \
          -F "product_name=WebGoat" \
          -F "engagement_name=edgar" \
          http://18.218.244.166:8080/api/v2/import-scan/
      env:
        api_key: ${{ secrets.API_KEY }}  
        type_scan: ${{ github.event.inputs.type_scan }}
