name: Docker Img

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: "Obteniendo ultima version del codigo"
        uses: actions/checkout@v2

      - name: "Instalacion Java"
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: "Instalación de jq"
        run: sudo apt-get -y install jq

      - name: "Dependency Check"
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Tool

        with:
          project: 'WebGoat'
          path: '.'
          format: 'HTML'
          out: 'reports'

      - name: "Verificar reporte"
        run: ls -ltra reports

      - name: "Construir imagen Docker"
        run: |
          docker build -t webgoat:latest .
        working-directory: ${{ github.workspace }}

      - name: "Verificar imagen Docker construida"
        run: |
          docker images
        working-directory: ${{ github.workspace }}