name: Pipeline Subir Reporte

on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: "Obteniendo última versión del código"
        uses: actions/checkout@v3

      - name: "Instalación de Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Compilación"
        run: ./mvnw clean install

      - name: "Verificar paquete"
        run: ls -ltra target

      - name: "Generación de imagen de Docker"
        run: |
          docker build -f Dockerfile -t webgoat .

      - name: Configuración de Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Actualizar python
        run: |
              pip3 install requests

      - name: "Dependency-check"
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'WebGoat'
          path: '.'
          format: 'XML'
          out: 'reporte'

      - name: Reflect Dojo Dependency check
        run: python3 import.py -f ${{github.workspace}}/reporte/dependency-check-report.xml -t "Dependency Check Scan"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          security-checks: 'vuln,secret,config'
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-results.json'

      - name: Reflect Dojo trivy
        run: python3 import.py -f ./trivy-results.json -t "Trivy Scan" 

  python-secret:
    name: Python Secret
    runs-on: ubuntu-latest

    env:
      api_key: ${{ secrets.API_KEY }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Configuración de Python 3.8"
        uses: actions/setup-python@v4
        with:
          python-version: 3.8