name: GOAT Compile

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build project with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: Verify the package
        run: ls -ltra target

  sca:
    runs-on: ubuntu-latest
    name: Dependency Check Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: Run Dependency-Check
        uses: dependency-check/dependency-check-action@v2
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java/17
        with:
          project: 'test'
          format: 'HTML'
          out: 'reports' # Default
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports