name: Subir reporte

on:
  push:
    branches:
      - main  

jobs:
  security_scan:
    runs-on: ubuntu-latest  

    steps:
      - name: Verificar el repositorio
        uses: actions/checkout@v2

      - name: Configurar entorno de Python
        uses: actions/setup-python@v2
        with:
          python-version: 3  

      - name: Instalar dependencias de Python
        run: pip install requests

      - name: Ejecutar Dependency-Check
        run: |
          python - <<EOF
          import requests
          import json

          url_api = "http://18.218.244.166:8080/api/v2/{method}"
          api_key = "Token edaf1740e048924e2f817fb6436a803b690c6900"

          def upload_report(file_report, type_scan):
              headers = {
                  'accept' : 'application/json',
                  'Authorization' : api_key 
              }

              reports = {
                  'file': open(file_report, 'rb')
              }

              body = {
                  'minimum_severity' : 'Info',
                  'active': True,
                  'verified': True,
                  'scan_type': type_scan,
                  'close_old_findings': False,
                  'test_title': 'EdgarPrueba',
                  'product_name': 'WebGoat',
                  'engagement_name': 'edgar'
              } 

              t = requests.post(url_api.format(method='import-scan/'), data = body, files = reports, headers = headers, verify = False)

              print(t.status_code)
              if t.status_code == 201:
                  print(json.dumps(t.json(), indent=4))

          if __name__ == '__main':  
              file_report = "$GITHUB_WORKSPACE/" + "${{ github.event.workflow_run.event.data.artifacts.upload_report.name }}"
              type_scan = "${{ github.event.workflow_run.event.data.artifacts.upload_report.name }}"
              upload_report(file_report, type_scan)
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
