name: DevSecOps-Test-AWS
 
on:
  push:
    branches:
      - main
 
jobs:
  integration:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
 
    steps:
      - name: "Obteniendo ultima version del codigo"
        uses: actions/checkout@v3
 
      - name: "Instalacion Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
 
      - name: "Compilacion"
        run: ./mvnw clean install
 
      - name: "Verificar paquete"
        run: ls -ltra target
 
      - name: "Generación de imagen de docker"
        run: |
          docker build -f Dockerfile -t webgoat .

      - name: "Configuracion de credenciales AWS"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.EDGARLABNOV2023AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.EDGARLABNOV2023AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1    

      - name: "Cargar imagen a ECR"
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i3l4a3q5/edgarv 
          docker tag webgoat public.ecr.aws/i3l4a3q5/
          docker push public.ecr.aws/i3l4a3q5/
        env:
          ECR_URL: public.ecr.aws/i3l4a3q5/ 

      - name: "Aprovisionamiento de Terraform"
        run: |
          cd terraform
          terraform initgit 
          terraform apply -auto-approve
